apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 2
  labels:
    run: smc-hub
  name: smc-hub
spec:
  replicas: {replicas}
  minReadySeconds: {min_read_seconds}
  selector:
    matchLabels:
      run: smc-hub
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: smc-hub
    spec:
      containers:
      - image: {image_hub}
        imagePullPolicy: {pull_policy}
        name: smc-hub
        ports:
        - containerPort: 5000
          protocol: TCP
        - containerPort: 5001
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /alive
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 45
          timeoutSeconds: 3
        resources:
          requests:
            cpu: 100m
            memory: "400Mi"
          limits:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - name: secret-rethinkdb
          mountPath: /secrets/rethinkdb/
          readOnly: true
        - name: secret-sendgrid
          mountPath: /secrets/sendgrid/
          readOnly: true
        - name: secret-zendesk
          mountPath: /secrets/zendesk/
          readOnly: true
        env:
          - name: SMC_DB_HOSTS
            value: {smc_db_hosts}
          - name: SMC_DB_POOL
            value: "{smc_db_pool}"
      - image: {image_rethinkdb_proxy}
        imagePullPolicy: {pull_policy}
        name: rethinkdb-proxy
        terminationMessagePath: /dev/termination-log
        ports:
        - containerPort: 28015
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /health.py
          initialDelaySeconds: 30
          timeoutSeconds: 3
        volumeMounts:
        - name: secret-rethinkdb
          mountPath: /secrets/rethinkdb/
          readOnly: true
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          requests:
            cpu: "150m"
            memory: "400Mi"
          limits:
            cpu: "2000m"
            memory: "2000Mi"
      volumes:
        - name: secret-rethinkdb
          secret:
            secretName: rethinkdb-password


      volumes:
        - name: secret-rethinkdb
          secret:
            secretName: rethinkdb-password
        - name: secret-sendgrid
          secret:
            secretName: sendgrid-api-key
        - name: secret-zendesk
          secret:
            secretName: zendesk-api-key
