apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: null
  generation: 1
  labels:
    run: smc-webapp-static
  name: smc-webapp-static
  selfLink: /apis/extensions/v1beta1/namespaces/deployments/smc-webapp-static
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      run: smc-webapp-static
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: smc-webapp-static
    spec:
      containers:
      - image: {image}
        imagePullPolicy: {pull_policy}
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          timeoutSeconds: 1
        name: smc-webapp-static
        ports:
        - containerPort: 80
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        resources:
          requests:
            memory: "{memory_request}"
            cpu   : "{cpu_request}"
          limits:
            memory: "128Mi"
            cpu   : "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        preemptible: "false"
