apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: haproxy
  name: haproxy
  selfLink: /apis/extensions/v1beta1/namespaces/deployments/haproxy
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      run: haproxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: haproxy
    spec:
      containers:
      - image: {image}
        imagePullPolicy: {pull_policy}
        name: haproxy
        livenessProbe:
          httpGet:
            path: /
            port: 1936
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        ports:
        # All http services
        - containerPort: 80
          protocol: TCP
        # https
        - containerPort: 443
          protocol: TCP
        # haproxy stats
        - containerPort: 1936
          protocol: TCP
        volumeMounts:
        - name: secret
          mountPath: /secret
          readOnly: true
        args:
        - --namespace={namespace}
      volumes:
        - name: secret
          secret:
            secretName: ssl-cert
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
