# This is really a template for generating the yaml that describes the deployments
# for each of the storage nodes.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run : storage{number}
  name: storage{number}
  selfLink: /apis/extensions/v1beta1/namespaces/deployments/storage
spec:
  replicas: 1
  selector:
    matchLabels:
      storage  : nfs
      instance : {number}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
          storage  : nfs
          instance : {number}
    spec:
      containers:
      - image: {image}
        imagePullPolicy: {pull_policy}
        name: storage{number}
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /projects
          name: storage-projects
        resources:
          requests:
            memory: "100Mi"
            cpu: "40m"
          limits:
            memory: "1000Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: storage-projects
        gcePersistentDisk:
          fsType: ext4
          pdName: {pd_name}
