# This is really a template for generating the yaml that describes the deployments
# for each of the storage nodes.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run : storage{number}
    storage  : projects
  name: storage{number}
  selfLink: /apis/extensions/v1beta1/namespaces/deployments/storage
spec:
  replicas: 1
  selector:
    matchLabels:
      storage  : projects
      instance : "{number}"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
          storage  : projects
          instance : "{number}"
    spec:
      containers:

      - image: "{image}-ssh"
        imagePullPolicy: {pull_policy}
        name: ssh
        securityContext:  # needed for ssh ports (?)
          privileged: true
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /ssh
          name: storage-ssh
        resources:
          requests:
            memory: "70Mi"
            cpu: "200m"
          limits:
            memory: "300Mi"
            cpu: "1000m"

      - image: "{image}-backup"
        imagePullPolicy: {pull_policy}
        name: backup
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /secrets/rethinkdb/
          name: secret-rethinkdb
          readOnly: true
        - mountPath: /secrets/gcloud/
          name: secret-gcloud-config
          readOnly: true
        env:
          - name: GCLOUD_BUCKET
            value: "{gcloud_bucket}"
        resources:
          requests:
            memory: "100Mi"
            cpu: "20m"
          limits:
            memory: "500Mi"
            cpu: "500m"

      - image: "{image}-open"
        imagePullPolicy: {pull_policy}
        name: open
        env:
          - name: STORAGE_SERVER
            value: "{number}"
          - name: GCLOUD_BUCKET
            value: "{gcloud_bucket}"
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /secrets/rethinkdb/
          name: secret-rethinkdb
          readOnly: true
        - mountPath: /secrets/gcloud/   # to use gsutil
          name: secret-gcloud-config
          readOnly: true
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "1000m"

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        gcePersistentDisk:
          fsType: ext4
          pdName: {pd_name}
      - name: storage-ssh
        secret:
          secretName: storage-ssh
      - name: secret-rethinkdb
        secret:
          secretName: rethinkdb-password
      - name: secret-gcloud-config
        secret:
          secretName: gcloud-config

