# This is really a template for generating the yaml that describes the deployments
# for each of the storage nodes.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-manager
  labels:
    run : cluster-manager
  annotations:
    deployment.kubernetes.io/revision: "1"
  selfLink: /apis/extensions/v1beta1/namespaces/deployments/cluster-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      run : cluster-manager
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
          run : cluster-manager
    spec:
      containers:
      - name: cluster-manager
        image: {image}
        imagePullPolicy: {pull_policy}
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "100Mi"
            cpu: "300m"
        env:
          - name: KUBERNETES_CLUSTER_PREFIX
            value: {cluster_prefix}
