apiVersion: v1
kind: Pod
metadata:
  name: nginx3
spec:
  containers:
  - name: nginx3
    image: nginx
    volumeMounts:
    - name: zfs
      mountPath: /zfs
    - name: zfs2
      mountPath: /zfs2
    - name: zfs3
      mountPath: /zfs3
    - name: zfs4
      mountPath: /zfs4
    - name: zfs5
      mountPath: /zfs5
    - name: zfs6
      mountPath: /zfs6
    - name: zfs7
      mountPath: /zfs7
    - name: zfs8
      mountPath: /zfs8
    - name: zfs9
      mountPath: /zfs9
    - name: zfs10
      mountPath: /zfs10
    - name: zfs11
      mountPath: /zfs11
    - name: zfs12
      mountPath: /zfs12
    ports:
    - containerPort: 80
  volumes:
  - name: zfs
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "tests2/0.zfs"
        size   : "1000m"
  - name: zfs2
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "tests2/zfs/1.zfs"
        size   : "10G"
  - name: zfs3
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "tests2/many/3.zfs"
        size   : "500m"
  - name: zfs4
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "tests2/many/4.zfs"
        size   : "500m"
  - name: zfs5
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "tests2/many/5.zfs"
        size   : "500m"
  - name: zfs6
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "tests2/many/6.zfs"
        size   : "500m"
  - name: zfs7
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "tests2/many/7.zfs"
        size   : "500m"
  - name: zfs8
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "tests2/many/8.zfs"
        size   : "500m"
  - name: zfs9
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "tests2/many/9.zfs"
        size   : "500m"
  - name: zfs10
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "tests2/many/10.zfs"
        size   : "500m"
  - name: zfs11
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "tests2/many/11.zfs"
        size   : "500m"
  - name: zfs12
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "tests2/many/12.zfs"
        size   : "500m"

  nodeSelector:
    volume: storage