apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  containers:
  - name: test1
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /test
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver : "smc/smc-storage"
      options:
        namespace : 'test'
        server    : 'storage0'
        path      : "abc.zfs"
        size      : "3000m"
